import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — NameRadar",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16">
      <Link href="/" className="text-sm text-brand-300 hover:text-brand-200">
        ← Back
      </Link>
      <h1 className="mt-6 text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: June 15, 2026</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-slate-300">
        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">1. The service</h2>
          <p>
            NameRadar brainstorms candidate company names and researches whether
            each appears to be in use on the public web. Results are generated by
            AI together with live web search and are provided on a best-effort
            basis.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">2. Not legal advice</h2>
          <p>
            Availability assessments are <strong>not</strong> a trademark search,
            domain registration check, or legal opinion. A name shown as
            &quot;available&quot; may still be trademarked, registered, or
            otherwise unavailable. Always perform formal trademark and
            registration due diligence before adopting a name. You are solely
            responsible for any name you choose to use.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">3. Credits & payments</h2>
          <p>
            Searches are paid for with credits. New accounts receive a free
            allotment of credits. Additional credits are sold in one-time packs
            and processed by Stripe. Credits are consumed per search; a credit is
            refunded automatically if a search fails to produce results. Purchased
            credits are non-transferable. Except where required by law, payments
            are non-refundable.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">4. Acceptable use</h2>
          <p>
            Do not abuse, automate, or attempt to overload the service, and do not
            use it for unlawful purposes. We may suspend accounts that violate
            these terms.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">5. Disclaimer</h2>
          <p>
            The service is provided &quot;as is&quot; without warranties of any
            kind. To the maximum extent permitted by law, NameRadar is not liable
            for any damages arising from your use of the service or reliance on its
            results.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-semibold text-white">6. Contact</h2>
          <p>Questions? Reach us at the email associated with your account.</p>
        </section>
      </div>
    </main>
  );
}
